# Generated by Django 4.2.7 on 2023-11-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0002_country_hotel_resort_tour_tourist_delete_bb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='beach_info',
            field=models.TextField(verbose_name='Информация о пляже'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='distance_from_airport',
            field=models.IntegerField(verbose_name='Расстояние от аэропорта (км)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btest.resort', verbose_name='Курорт'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(verbose_name='Звездный рейтинг'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btest.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название курорта'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btest.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='return_date',
            field=models.DateField(verbose_name='Дата возвращения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='room_type',
            field=models.CharField(max_length=255, verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btest.tourist', verbose_name='Турист'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя туриста'),
        ),
    ]
